from dataclasses import dataclass

@dataclass
class DataIngestionArtifact:
    books_file_path:str
    users_file_path:str
    ratings_file_path:str

class DataTransformationArtifact:...
class ModelTrainingArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...